### ISSUE TITLE
Facet children are but updated within hierarchical-Menu when using keepZeroFacets

### ISSUE THREAD

**Issue by schorschebob** [meilisearch/meilisearch-js-plugins#1040]
**Description**
I use a hierarchical menu to filter an index based on a facet configuration. To display all categories regardless of the search query, I set `keepZeroFacets` to `true`.

**Current behavior**
The child facets are not displayed when a root facet is selected. If I use a router, select a facet, and then reload the page, the child facets are displayed.

**Expected behavior**
Display of child facets when selecting a facet with children.

**Screenshots or logs**
Not displaying when selecting:
![Screenshot 2023-03-22 122429](https://user-images.githubusercontent.com/6859554/226890334-02a52669-d646-44d4-ad65-4a82fb66644d.png)
After site reload when using a HistoryRouter:
![Screenshot 2023-03-22 122441](https://user-images.githubusercontent.com/6859554/226890343-00aa14bc-9ff3-4dff-a448-4632e249ac0e.png)

**Environment (please complete the following information):**
- OS:  WSL2 with Debian GNU/Linux 11 (Windows 11 22H2)
- Browser: Mozilla Firefox v111.0 (64-Bit)
- Meilisearch version: v1.0.2
- instant-meilisearch version: v0.11.1
- instantsearch.js version: v4.8.8 (vue-instantsearch)

**Comment by dsuppiger** [comment]
Could you give this some priority? It's breaking one of my projects.

**Comment by bidoubiwa** [comment]
Hey @schorschebob 
I'll give it a look this week!

**Comment by bidoubiwa** [comment]
I indeed could reproduce the bug. I suppose it comes from the way I store the zero facet distribution. Currently it only handles facets on first and second level. The solution would be to recursively crawl into every nested facet and store them.

**Comment by engel-m** [comment]
@bidoubiwa any update on this? I am running into the exact same issue with my hierarchical menus. After a page refresh (same URL) it also works for me, but for users this is very breaking of course.

**Comment by dsuppiger** [comment]
@bidoubiwa Has there been any progress on this?

**Comment by dsuppiger** [comment]
Thanks for the fix 🥳🥳
