### ISSUE TITLE
Sorting with _geoPoint splits coordinates into two arrays at the comma (instant-meilisearch)

### ISSUE THREAD

**Issue by sg-code** [meilisearch/meilisearch-js-plugins#1159]
**Description**
When attempting to sort by _geoPoint, the correctly formatted request is split into two arrays at the comma, mid string. For example, a request to sort:

```javascript
"indexName:_geoPoint(37.8153, -122.4784):asc"
```
is transformed to:

```javascript
queries: [{
   // ...
   sort: [
      "indexName:_geoPoint(37.8153",
      "-122.4784):asc"
   ]
}]
```
within the request payload sent to the Meilisearch server. As one might imagine, this completely breaks geo sorting functionality. The following error is returned to the browser:

```
Error: MeiliSearchApiError: Inside `.queries[0]`: Invalid syntax for the sort parameter: expected expression ending by `:asc` or `:desc`, found `_geoPoint(37.8153`.
```

**Expected behavior**
The query payload should return:

```javascript
queries: [{
   // ...
   sort: ["indexName:_geoPoint(37.8153, -122.4784):asc"]
}]
```

**Current behavior**
It is clear to me this behavior is coming from the `createSortState` function exported from [meilisearch-js-plugins/packages/instant-meilisearch/src/contexts/sort-context.ts](https://github.com/meilisearch/meilisearch-js-plugins/blob/5ae277c8f9129eafedbbde9a453a5024fe50cad8/packages/instant-meilisearch/src/contexts/sort-context.ts#L5), which splits the `rawSort` input at commas. As noted in the [Meilisearch Sort documentation](https://www.meilisearch.com/docs/learn/advanced/sorting#sorting-with-_geopoint), the _geoPoint syntax must include a comma to delineate lat/lng coordinates, and thus the `createSortState` function completely breaks _geoPoint sorting functionality.

I'm not sure what the utility of `rawSort.split(',')` is, but hopefully an exception can be added for coordinate based geosearch operations.

**Environment**
- OS: MacOS Ventura 13.3
- Browser: Chrome v114.0.5735.106
- Meilisearch version: v1.1.0
- instant-meilisearch version: v0.13.2
- instantsearch.js version: v4.53.0
- react-instantsearch-hooks-web: v6.44.1

**Comment by bidoubiwa** [comment]
Hey @sg-code 

This is a bug that should be fixed. I never considered that a geo filter could be provided through the sortBy plugin!

**Comment by bidoubiwa** [comment]
> I'm not sure what the utility of rawSort.split(',') is, but hopefully an exception can be added for coordinate based geosearch operations.

It's possible to provide multiple rules like this:

```
indexName: 'movies:release_date:desc,title:asc',
```

Thats why it's split on `,`.

**Comment by sg-code** [comment]
@bidoubiwa Thanks for looking into this!
