### ISSUE TITLE
Search on facet values when sorting

### ISSUE THREAD

**Issue by Strift** [meilisearch/meilisearch-js-plugins#1222]
**Description**
- can't search for facet values when sorting

**Expected behavior**
- facet search should work

**Current behavior**
- facet search does not work after applying sorting

**Reproduction**
- navigate to [ecommerce.meilisearch.com](http://ecommerce.meilisearch.com/)
- sort product eg. by price (on the right) — this works
- search in the “category” facet input — this doesn’t

Errors in the console

```
POST https://ms-41598e7e5e23-106.sfo.meilisearch.io/indexes/products:price:asc/facet-search 400

Uncaught (in promise) MeiliSearchApiError: `products:price:asc` is not a valid index uid. Index uid can be an integer or a string containing only alphanumeric characters, hyphens (-) and underscores (_).
    at entry.db00d9dc.js:5:47462
    at Generator.next (<anonymous>)
    at a (entry.db00d9dc.js:5:46195)
```

**Environment (please complete the following information):**
- Meilisearch version: v1.3.0
- instant-meilisearch version: v0.13.4

**Comment by lrojas94** [comment]
Can confirm this is the case. 
From what I can tell, this happens because of how Angolia sorting works (via Index name). It passes the wrong index name to MeiliSearch (in the case above, `products:price:asc`).

**Comment by bidoubiwa** [comment]
Hey everyone! 
We'll be fixing this bug very soon. Thanks for raising it :)
