### ISSUE TITLE
Expose search parameters intuitively, specifically the important ones (`attributesToHighlight`, `attributesToCrop`, …)

### ISSUE THREAD

**Issue by flevi29** [meilisearch/meilisearch-js-plugins#1249]
**Description**
I can see that [`attributesToSearchOn`](https://github.com/meilisearch/product/discussions/107#discussioncomment-6607245) was implemented. Wish we could use it within this plugin, can we? Am I missing something?

**Basic example**
I imagine this would involve having the ability to change the settings dynamically of the search adapter. At the very least this setting.
I'd use this to give the ability to users to dynamically select the fields they wish to search on.

**Comment by flevi29** [comment]
Upon further investigation I determined that access to the search parameters is simply not implemented in any way.
The only way I could tinker with it is through custom `httpClient`
```typescript
httpClient: (input, init) => {
            if (init !== undefined) {
              const parsedBody = JSON.parse(<string>init.body);
              console.log(parsedBody);
              // modify parsedBody and then
              // init.body = JSON.stringify(parsedBody);
            }
            return fetch(input, init);
          },
```

However at this point Angular gets in the way with its ridiculous outdated `NgZone`, so this keeps throwing, I really hope that's the only issue, will look into it more.

<details>
  <summary>Error</summary>

```  
ERROR Error: Uncaught (in promise): Error: TypeError: searchResponses.results is undefined
5512/</instantMeiliSearch/search/</<@http://127.0.0.1:4200/src_app_modules_instantsearch_instantsearch_component_ts-node_modules_pnpm_rxjs_7_8_1_node_mo-bbdcbb.js:9375:23
step@http://127.0.0.1:4200/src_app_modules_instantsearch_instantsearch_component_ts-node_modules_pnpm_rxjs_7_8_1_node_mo-bbdcbb.js:4392:19
5512/</__generator/verb/<@http://127.0.0.1:4200/src_app_modules_instantsearch_instantsearch_component_ts-node_modules_pnpm_rxjs_7_8_1_node_mo-bbdcbb.js:4341:16
rejected@http://127.0.0.1:4200/src_app_modules_instantsearch_instantsearch_component_ts-node_modules_pnpm_rxjs_7_8_1_node_mo-bbdcbb.js:4307:26
invoke@http://127.0.0.1:4200/polyfills.js:8210:158
onInvoke@http://127.0.0.1:4200/vendor.js:54550:25
invoke@http://127.0.0.1:4200/polyfills.js:8210:46
run@http://127.0.0.1:4200/polyfills.js:7992:35
8108/</scheduleResolveOrReject/<@http://127.0.0.1:4200/polyfills.js:9071:28
invokeTask@http://127.0.0.1:4200/polyfills.js:8237:171
onInvokeTask@http://127.0.0.1:4200/vendor.js:54230:22
invokeTask@http://127.0.0.1:4200/polyfills.js:8237:54
onInvokeTask@http://127.0.0.1:4200/vendor.js:54539:25
invokeTask@http://127.0.0.1:4200/polyfills.js:8237:54
runTask@http://127.0.0.1:4200/polyfills.js:8038:37
drainMicroTaskQueue@http://127.0.0.1:4200/polyfills.js:8408:23
promise callback*nativeScheduleMicroTask@http://127.0.0.1:4200/polyfills.js:8385:18
scheduleMicroTask@http://127.0.0.1:4200/polyfills.js:8395:30
scheduleTask@http://127.0.0.1:4200/polyfills.js:8229:28
onScheduleTask@http://127.0.0.1:4200/vendor.js:54223:21
scheduleTask@http://127.0.0.1:4200/polyfills.js:8222:43
onScheduleTask@http://127.0.0.1:4200/polyfills.js:8139:61
scheduleTask@http://127.0.0.1:4200/polyfills.js:8222:43
scheduleTask@http://127.0.0.1:4200/polyfills.js:8077:35
scheduleMicroTask@http://127.0.0.1:4200/polyfills.js:8096:19
scheduleResolveOrReject@http://127.0.0.1:4200/polyfills.js:9061:10
resolvePromise@http://127.0.0.1:4200/polyfills.js:9002:34
8108/</makeResolver/<@http://127.0.0.1:4200/polyfills.js:8920:23
8108/</once/wrapper/<@http://127.0.0.1:4200/polyfills.js:8936:25
promise callback*8108/</patchThen/Ctor.prototype.then/wrapped<@http://127.0.0.1:4200/polyfills.js:9298:22
ZoneAwarePromise@http://127.0.0.1:4200/polyfills.js:9223:21
8108/</patchThen/Ctor.prototype.then@http://127.0.0.1:4200/polyfills.js:9297:23
resolvePromise@http://127.0.0.1:4200/polyfills.js:8967:16
8108/</makeResolver/<@http://127.0.0.1:4200/polyfills.js:8920:23
8108/</once/wrapper/<@http://127.0.0.1:4200/polyfills.js:8936:25
5512/</meilisearch_umd</</__awaiter/adopt/<@http://127.0.0.1:4200/src_app_modules_instantsearch_instantsearch_component_ts-node_modules_pnpm_rxjs_7_8_1_node_mo-bbdcbb.js:5011:20
ZoneAwarePromise@http://127.0.0.1:4200/polyfills.js:9223:21
adopt@http://127.0.0.1:4200/src_app_modules_instantsearch_instantsearch_component_ts-node_modules_pnpm_rxjs_7_8_1_node_mo-bbdcbb.js:5010:47
step@http://127.0.0.1:4200/src_app_modules_instantsearch_instantsearch_component_ts-node_modules_pnpm_rxjs_7_8_1_node_mo-bbdcbb.js:5030:51
5512/</meilisearch_umd</</__awaiter/<@http://127.0.0.1:4200/src_app_modules_instantsearch_instantsearch_component_ts-node_modules_pnpm_rxjs_7_8_1_node_mo-bbdcbb.js:5032:15
ZoneAwarePromise@http://127.0.0.1:4200/polyfills.js:9223:21
__awaiter@http://127.0.0.1:4200/src_app_modules_instantsearch_instantsearch_component_ts-node_modules_pnpm_rxjs_7_8_1_node_mo-bbdcbb.js:5014:16
request@http://127.0.0.1:4200/src_app_modules_instantsearch_instantsearch_component_ts-node_modules_pnpm_rxjs_7_8_1_node_mo-bbdcbb.js:5297:20
_callee3$@http://127.0.0.1:4200/src_app_modules_instantsearch_instantsearch_component_ts-node_modules_pnpm_rxjs_7_8_1_node_mo-bbdcbb.js:5391:33
tryCatch@http://127.0.0.1:4200/src_app_modules_instantsearch_instantsearch_component_ts-node_modules_pnpm_rxjs_7_8_1_node_mo-bbdcbb.js:4519:23
5512/</meilisearch_umd</</_regeneratorRuntime/wrap/generator._invoke@http://127.0.0.1:4200/src_app_modules_instantsearch_instantsearch_component_ts-node_modules_pnpm_rxjs_7_8_1_node_mo-bbdcbb.js:4502:38
5512/</meilisearch_umd</</_regeneratorRuntime/defineIteratorMethods/</<@http://127.0.0.1:4200/src_app_modules_instantsearch_instantsearch_component_ts-node_modules_pnpm_rxjs_7_8_1_node_mo-bbdcbb.js:4544:27
5512/</meilisearch_umd</</__awaiter/<@http://127.0.0.1:4200/src_app_modules_instantsearch_instantsearch_component_ts-node_modules_pnpm_rxjs_7_8_1_node_mo-bbdcbb.js:5032:73
ZoneAwarePromise@http://127.0.0.1:4200/polyfills.js:9223:21
__awaiter@http://127.0.0.1:4200/src_app_modules_instantsearch_instantsearch_component_ts-node_modules_pnpm_rxjs_7_8_1_node_mo-bbdcbb.js:5014:16
post@http://127.0.0.1:4200/src_app_modules_instantsearch_instantsearch_component_ts-node_modules_pnpm_rxjs_7_8_1_node_mo-bbdcbb.js:5386:20
_callee10$@http://127.0.0.1:4200/src_app_modules_instantsearch_instantsearch_component_ts-node_modules_pnpm_rxjs_7_8_1_node_mo-bbdcbb.js:7896:45
tryCatch@http://127.0.0.1:4200/src_app_modules_instantsearch_instantsearch_component_ts-node_modules_pnpm_rxjs_7_8_1_node_mo-bbdcbb.js:4519:23
5512/</meilisearch_umd</</_regeneratorRuntime/wrap/generator._invoke@http://127.0.0.1:4200/src_app_modules_instantsearch_instantsearch_component_ts-node_modules_pnpm_rxjs_7_8_1_node_mo-bbdcbb.js:4502:38
5512/</meilisearch_umd</</_regeneratorRuntime/defineIteratorMethods/</<@http://127.0.0.1:4200/src_app_modules_instantsearch_instantsearch_component_ts-node_modules_pnpm_rxjs_7_8_1_node_mo-bbdcbb.js:4544:27
5512/</meilisearch_umd</</__awaiter/<@http://127.0.0.1:4200/src_app_modules_instantsearch_instantsearch_component_ts-node_modules_pnpm_rxjs_7_8_1_node_mo-bbdcbb.js:5032:73
ZoneAwarePromise@http://127.0.0.1:4200/polyfills.js:9223:21
__awaiter@http://127.0.0.1:4200/src_app_modules_instantsearch_instantsearch_component_ts-node_modules_pnpm_rxjs_7_8_1_node_mo-bbdcbb.js:5014:16
multiSearch@http://127.0.0.1:4200/src_app_modules_instantsearch_instantsearch_component_ts-node_modules_pnpm_rxjs_7_8_1_node_mo-bbdcbb.js:7889:20
```
  
</details>

On a side note while debugging this, I also realized that Angular upon seeing `"browser"` entry in package.json, will automatically choose that. What if I want the ESM code? The UMD one is twice as long, and I don't want to support Internet Explorer, or whatever purpose UMD is supposed to serve here. Maybe should open a separate issue on the usage of [`"exports"`](https://nodejs.org/api/packages.html#subpath-exports).

**Comment by bidoubiwa** [comment]
Hey @flevi29 
Indeed, there is no access to the search parameters. It's a nice feature that is easily implemented if you'd like to contribute!

**Comment by flevi29** [comment]
My time is limited atm, but if I do find the time, I'll try to.

**Comment by flevi29** [comment]
I was researching a bit and one questionable thing I've stumbled upon is `highlightPreTag` and `highlightPostTag`. The way I see it, the default value for these is only required if the user wants to enable `escapeHTML` in the `hits` widget, this option escapes some HTML characters but also replaces `__ais-highlight__` with `<mark>` and similarly for the post tag.

I guess they'll change this behavior as they left the following comment `// @MAJOR: in the future, this should only escape, not replace`, but who knows when.

Looking at this for a while made me question the whole concept, the ideal solution would be to get the position of the highlights, like with `showMatchesPosition`, however I am unsure about it because of the byte length thing and I don't even know what consequences exactly comes with `showMatchesPosition returns the location of matched query terms within all attributes, even attributes that are not set as searchableAttributes.` or what it really means.

Should we allow to customize these two options, and in the docs warn the users to not enable `escapeHTML` in the `hits` widget if they do so, and implement their own `escapeHTML` (or whatever implementation they might use, like splitting the string) ?

I am unsure if this would work with the framework libraries, but for simple connector implementations this would be fine.

**Comment by flevi29** [comment]
Should these new settings override the ones that are coming from `instantsearch.js`?
For instance:
```typescript
    addPreTag() {
      meiliSearchParams.highlightPreTag =
        overrideParameters?.highlightPreTag ??
        highlightPreTag ??
        '__ais-highlight__'
    }
```
Should only the following parameters be configurable?
```typescript
export type ConfigurableMeiliSearchSearchParameters = Pick<
  MeiliSearchMultiSearchParams,
  | 'attributesToRetrieve'
  | 'attributesToCrop'
  | 'cropLength'
  | 'cropMarker'
  | 'attributesToHighlight'
  | 'highlightPreTag'
  | 'highlightPostTag'
  | 'showMatchesPosition'
  | 'matchingStrategy'
  | 'showRankingScore'
  | 'attributesToSearchOn'
>
```

**Comment by bidoubiwa** [comment]
I agree with you, they should overwrite them!

The user could also provide these params whenever they init the search client:

```js
const client = instantMeilisearch(host, url, { meilisearchParams: {...} }
```

About the highlighting parameter, it might be worth it's own PR to answer these questions.

**Comment by flevi29** [comment]
https://github.com/meilisearch/meilisearch-js-plugins/blob/26ce5c31cef7ef16a45bd79e24d9a9f3065d1520/packages/instant-meilisearch/src/adapter/search-request-adapter/search-params-adapter.ts#L102-L108

I can see that this is checked against `string`, but the current Algolia API doesn't support `string`, according to the types and to the [docs](https://www.algolia.com/doc/api-reference/api-parameters/facets/).
The reason (at least one of them) you might've kept it around could be that you're also using [`react-router-dom`](https://www.npmjs.com/package/react-instantsearch-dom?activeTab=versions), which was deprecated **2** years ago, which I assume doesn't even support the latest Algolia version.

Do we really want to support this? I propose moving away from `react-router-dom` and to [`react-instantsearch`](https://www.npmjs.com/package/react-instantsearch). Should this be a new PR, and for the time being keep checking against `string`?

**Comment by flevi29** [comment]
```typescript
const { searchClient, setMeiliSearchParams } = instantMeiliSearch(
      'http://localhost:7700',
      'masterKey',
      {
        meiliSearchParams: {
          highlightPreTag: '<em>',
          highlightPostTag: '</em>',
          attributesToSearchOn: ['overview'],
        },
      }
    )
```
This would be the new return of `instantMeiliSearch`. Is this fine? I think this would need a major version bump. Should I find a different way? I am not sure if there are better options.

**Comment by flevi29** [comment]
> https://github.com/meilisearch/meilisearch-js-plugins/blob/26ce5c31cef7ef16a45bd79e24d9a9f3065d1520/packages/instant-meilisearch/src/adapter/search-request-adapter/search-params-adapter.ts#L102-L108
> 
> I can see that this is checked against `string`, but the current Algolia API doesn't support `string`, according to the types and to the [docs](https://www.algolia.com/doc/api-reference/api-parameters/facets/). The reason (at least one of them) you might've kept it around could be that you're also using [`react-instantsearch-dom`](https://www.npmjs.com/package/react-instantsearch-dom?activeTab=versions), which was deprecated **2** years ago, which I assume doesn't even support the latest Algolia version.
> 
> Do we really want to support this? I propose moving away from `react-instantsearch-dom` and to [`react-instantsearch`](https://www.npmjs.com/package/react-instantsearch). Should this be a new PR, and for the time being keep checking against `string`?

Never mind, tested with latest and greatest `react-instantsearch`, still sends facets as string. Maybe there's more to it.
