### ISSUE TITLE
Error when choosing a facet containing quotation marks (`"` character)

### ISSUE THREAD

**Issue by flevi29** [meilisearch/meilisearch-js-plugins#1256]
**Description**
When using a facet that contains `"` characters, the `filter` parameter has it's backslashes not properly escaped (I think), which causes an error.

<details>
<summary>Query body</summary>

```
{
  "queries": [
    {
      "q": "",
      "indexUid": "i",
      "facets": [
        "document_type",
        "imprint.publication_place",
        "imprint.publisher_name",
        "languages",
        "library",
        "other_authors",
        "primary_author",
        "publication_year",
        "religion",
        "subjects"
      ],
      "attributesToHighlight": [
        "*"
      ],
      "highlightPreTag": "__ais-highlight__",
      "highlightPostTag": "__/ais-highlight__",
      "hitsPerPage": 10,
      "page": 1,
      "filter": [
        [
          "\"imprint.publisher_name\"=\"\"MAgyar Őskutatás\" K.\""
        ]
      ]
    },
    {
      "q": "",
      "indexUid": "i",
      "facets": [
        "imprint.publisher_name"
      ],
      "attributesToHighlight": [
        "*"
      ],
      "highlightPreTag": "__ais-highlight__",
      "highlightPostTag": "__/ais-highlight__",
      "hitsPerPage": 0,
      "page": 1
    }
  ]
}
```
</details>

<details>
<summary>Error message</summary>

```
MeiliSearchApiError: Inside `.queries[0]`: Found unexpected characters at the end of the filter: `MAgyar Őskutatás\" K.\"`. You probably forgot an `OR` or an `AND` rule.
28:49 "imprint.publisher_name"=""MAgyar Őskutatás" K."
```
</details>

**Environment:**
- Meilisearch version: v1.4.0, v1.3.3, v1.3.5
- instant-meilisearch version: v0.13.6
- instantsearch.js version: v4.57.0

**Comment by curquiza** [comment]
Hello @flevi29 

Thank you for the report!

We are available to review any PR fixing the issue!

**Comment by flevi29** [comment]
https://github.com/meilisearch/meilisearch-js-plugins/blob/26ce5c31cef7ef16a45bd79e24d9a9f3065d1520/packages/instant-meilisearch/src/adapter/search-request-adapter/filter-adapter.ts#L3-L18
This should be changed to something like the following, then perhaps
```typescript
function transformFilter(filter: string): string {
  // What if there are escaped `:` characters? What about the rest of the operators?
  const [attribute, value] = filter.replace(/([\\"])/g, "\\$1").split(":");
  return `"${attribute}"="${value}"`;
}
```
This accounts for the new backslash change too. However I am unsure about a few things.
Is it possible that `filter` might contain somewhere an escaped `:` like `\:`? What about the rest of the operators? Will it always be `:`?

**Comment by flevi29** [comment]
Oh never mind, this won't work for numeric filters.
Actually why is it even called on numeric filters? It's not doing anything to it, the current version.
Should we handle [numeric filters](https://www.algolia.com/doc/api-reference/api-parameters/filters/#numeric-comparisons) differently? Should anything be escaped from these? Perhaps `attribute` if it contains any `.` -s? Can any of the operators appear in the name, and should they be escaped, or is it enough to just wrap the `attribute` in quotation marks (`"..."`)?
