### ISSUE TITLE
Query with special character (`"`) is not filtering correctly

### ISSUE THREAD

**Issue by gyto** [meilisearch/meilisearch-js-plugins#1261]
**Description**
When I select one of the items from the Refinement List I expect the search to work with cases when the item is `Awesome "Pepsi"`

I assume that search has to be represented as `"model"="Awesome \"Pepsi\"" however Meilisearch doesn't pick up the option I am searching for and crashes the search.

Is there a particular way to work around by replacing the meilisearch with instantsearch default filter options like `model:awe` or overwriting the routing of InstantSearch context?

```
MeiliSearchApiError: Inside `.queries[0]`: Found unexpected characters at the end of the filter: `Pepsi\"\"`. You probably forgot an `OR` or an `AND` rule.
25:32 "model"="Master II "Pepsi""
```

**Environment (please complete the following information):**
- OS: MacOS
- Browser: Chrome latest
- Meilisearch version: 1.4.0
- instant-meilisearch version: 0.13.6
- instantsearch.js version: 7.1.0

**Comment by flevi29** [comment]
https://github.com/meilisearch/meilisearch-js-plugins/pull/1259 should fix it.

**Comment by gyto** [comment]
@flevi29 is that a common issue for double quotes?

**Comment by flevi29** [comment]
Meilisearch filter requires you to escape `'` within `'...'` and `"` within `"..."` and the backslash `\\` itself of course, cause these characters have special meaning.

**Comment by gyto** [comment]
I think Algolia already does it on their end, escaping the quotes. Because all values of hit `value` is already escaped with `ABC \"etc\"`. Do you think is it possible to achieve this by using custom routing on InstantSearch Context? (rewriting route to handle custom behavior)

**Comment by curquiza** [comment]
Closing this in favor of https://github.com/meilisearch/meilisearch-js-plugins/issues/1256

Let me know if I'm wrong and it's not the same issue, but #1269 should indeed fix it
