### ISSUE TITLE
Prevent duplicate requests

### ISSUE THREAD

**Issue by chrissshh** [meilisearch/meilisearch-js-plugins#1267]
Instantsearch sends multiple duplicate requests to fetch results when first loading the search page using instantMeilisearch and it seems to happen with this component using the more with the useRefinementList hook. Instantsearch with algolia has an option to deduplicate requests using request cache but I can't find similar functionality with Meilisearch.
I'm using the newest versions of react-instantsearch and instant-meilisearch.

Does anyone know how to fix this because I've tried just about everything. Thanks!!

```
function XRefinementList({
  attribute,
}: {
  attribute: string;
}) {
  const { items, refine } = useRefinementList({
    attribute: attribute,
    sortBy: ["count:desc", "name:asc"],
  });

  return (
    <div>
      {items.map((item) => (
        <div key={item.label}>
          <button
            type="button"
            onClick={() => {
              refine(item.value);
            }}
            disabled={item.count === 0}
          >
            {item.label}
          </button>
        </div>
      ))}
    </div>
  );
}
```

**Comment by brunoocasali** [comment]
Hi @chrissshh thanks for the report!

Our time has been very compromised these last months, and we decided not to do support in the issues sections of our integrations repositories. 

**But you're not alone!** We have a very active community on [discord](https://discord.gg/meilisearch) that you could ask, and I'm sure someone will help you out!

Thanks for your comprehension! 

Cheers'
