### ISSUE TITLE
Sarafi webkit: SyntaxError: Invalid regular expression: invalid group specifier name (js-regexp-lookbehind)

### ISSUE THREAD

**Issue by brentnd** [meilisearch/meilisearch-js-plugins#1277]
**Description**
`SyntaxError: Invalid regular expression: invalid group specifier name` when loading on Safari Version 15.5 (17613.2.7.1.8).

**Current behavior**
On import of `@meilisearch/instant-meilisearch`, an exception is thrown by older browsers due to RegExp. 

The code in question in `src/adapter/search-request-adapter/filter-adapter.ts`:
```
// Matches first occurrence of an operator
const numericSplitRegExp = /(?<!(?:[<!>]?=|<|>|:).*)([<!>]?=|<|>|:)/
```

Use case is using `searchClient` from `instantMeiliSearch` with `getMeilisearchResults` from `@meilisearch/autocomplete-client`.

The RegExp bug: https://caniuse.com/js-regexp-lookbehind

**Screenshots or Logs**

Stack trace:
```
SyntaxError: Invalid regular expression: invalid group specifier name
RegExp — filter-adapter.ts:33
Module Code — filter-adapter.ts:33
evaluate
moduleEvaluation
moduleEvaluation
moduleEvaluation
moduleEvaluation
moduleEvaluation
(anonymous function)
promiseReactionJob
createInertiaApp.ts:38
```

**Environment (please complete the following information):**
- OS: MacOS
- Browser: Safari Version 15.5 (17613.2.7.1.8)
- Meilisearch version: v1.3.5
- instant-meilisearch version: 0.14.0
- instantsearch.js version: N/A, autocomplete only

**Comment by curquiza** [comment]
Hello @brentnd 

Thanks for the report

Any contribution are welcome ❤️

**Comment by brentnd** [comment]
Not a fix but as a work-around, I used `patch-package` with:

`patches/@meilisearch+instant-meilisearch+0.14.0.patch`
```patch
diff --git a/node_modules/@meilisearch/instant-meilisearch/src/adapter/search-request-adapter/filter-adapter.ts b/node_modules/@meilisearch/instant-meilisearch/src/adapter/search-request-adapter/filter-adapter.ts
index a0b8efe..858f873 100644
--- a/node_modules/@meilisearch/instant-meilisearch/src/adapter/search-request-adapter/filter-adapter.ts
+++ b/node_modules/@meilisearch/instant-meilisearch/src/adapter/search-request-adapter/filter-adapter.ts
@@ -30,7 +30,7 @@ function transformFacetFilter(filter: string): string {
 }

 // Matches first occurrence of an operator
-const numericSplitRegExp = /(?<!(?:[<!>]?=|<|>|:).*)([<!>]?=|<|>|:)/
+const numericSplitRegExp = /()/

 /**
  * Transform InstantSearch [numeric filter](https://www.algolia.com/doc/api-reference/api-parameters/numericFilters/)
```

Obviously removing the regex breaks the numeric filter transformation but in my case, I wasn't using any numeric filters in autocomplete so I was okay with that. Regular expressions aren't my strong-suit so I couldn't come up with one that doesn't use look behind but accomplishes the same thing.

Because this patch is patching `src` and not `dist`, I also needed to change my imports to `@meilisearch/autocomplete-client/src` where applicable.

**Comment by papaIOprog** [comment]
Hello @curquiza
I created a PR with a bug fix.
It can be messy, but I tried.

Also, I noticed that original `splitSortString` function breaks on this example.
```
Input: 'title:asc,_geoPoint(37.8153, -122.4784):asc,description:desc'
Output: ["title:asc,_geoPoint(37.8153, -122.4784):asc", "description:desc"]
```

But it works on example from comment
```
Input: '_geoPoint(37.8153, -122.4784):asc,title:asc,description:desc'
Output: [ '_geoPoint(37.8153, -122.4784):asc', 'title:asc', 'description:desc', ]
```

So I fixed that as well. Now it works like this:
```
Input: 'title:asc,_geoPoint(37.8153, -122.4784):asc,description:desc'
Output: [ "title:asc", "_geoPoint(37.8153, -122.4784):asc", "description:desc" ]
```

**Comment by brentnd** [comment]
Thanks for the quick turnaround on a PR, @papaIOprog.
