### ISSUE TITLE
Module build failed: UnhandledSchemeError: Reading from "node:crypto" with nextjs and 0.21.0

### ISSUE THREAD

**Issue by luluhoc** [meilisearch/meilisearch-js-plugins#1330]
**Description**
I'm getting this error with 0.21.0 on "^0.20.1" there is no error
```
 ⨯ node:crypto
Module build failed: UnhandledSchemeError: Reading from "node:crypto" is not handled by plugins (Unhandled scheme).
Webpack supports "data:" and "file:" URIs by default.
You may need an additional plugin to handle "node:" URIs.
Import trace for requested module:
node:crypto
./node_modules/@meilisearch/instant-meilisearch/dist/instant-meilisearch.umd.js
./src/lib/search-client.ts
./src/modules/mobile-menu/components/search-menu/index.tsx
./src/modules/layout/templates/nav/index.tsx
 GET /en 500 in 14107ms
 GET /en 500 in 23ms
```

**Expected behavior**
What you expected to happen.

**Current behavior**
What happened.

**Screenshots or Logs**
If applicable, add screenshots or logs to help explain your problem.

**Environment (please complete the following information):**
- OS: [e.g. Debian GNU/Linux]
- Browser: [e.g. Chrome version 90.0]
- Meilisearch version: [e.g. v.0.20.0]
- instant-meilisearch version: [e.g. v0.5.0]
- instantsearch.js version: [e.g. v4.23.0]

**Comment by sgilberg** [comment]
I see this is marked as closed but I'm still seeing this error, compiling with webpack (via Laravel Mix). Perhaps awaiting merge and release of https://github.com/meilisearch/meilisearch-js/pull/1739?
