### ISSUE TITLE
[v1.12.0] Adapt tests to new Meilisearch highlight behavior

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch-js-plugins#1340]
Related to https://github.com/meilisearch/integration-guides/issues/307

### Explanation of the feature

Related to this PR: https://github.com/meilisearch/meilisearch/pull/4928

The above PR led to changes in highlight behavior (checked internally with the engine team, these are expected). We need to adapt the tests of instant-meilisearch

### TODO

- [ ] Adapt the breaking test to the new Meilisearch behavior

⚠️ Make PRs pointing to `bump-meilisearch-v1.12.0` and NOT `main`. Please do 1 PR for all of these changes, and not several.

**Comment by curquiza** [comment]
@Strift I merged #1341
but tests are still failing in https://github.com/meilisearch/meilisearch-js-plugins/pull/1339 `Pre-Release Tests / instant-meilisearch end-to-end-tests`
so I don't close this issue yet 🐦‍

**Comment by Strift** [comment]
Yes, I've requested assistance from @ManyTheFish to investigate why this test might fail. It's related to [searching facet values](https://github.com/issues/assigned), so these tests should not be failing as far as I understand.

**Comment by curquiza** [comment]
This test is now fixed with rc6 🎉
