### ISSUE TITLE
Update testing and linting dependencies

### ISSUE THREAD

**Issue by bidoubiwa** [meilisearch/meilisearch-js-plugins#706]
Some dev dependencies, specifically these about linting and testing, are not automatically updated every Monday. 
Some of them are becoming not compatible with certain version of dependencies we do update. For example typescript-eslint and typescript itself. 

Thus, we should update all of the outdated dependencies. 
Use
`npm outdated` to find them.

**Comment by tanishk-23** [comment]
@bidoubiwa can you assign this issue to me?

**Comment by bidoubiwa** [comment]
Not critical and stale, closing
