### ISSUE TITLE
React Native compatibility hint

### ISSUE THREAD

**Issue by benhowes** [meilisearch/meilisearch-js-plugins#730]
Hi!

I've just experimented with replacing Algolia with Meilisearch in my react-native application. I had a bit of a problem for a while which turned out to be that I needed a polyfill for `URL` on RN. I added https://www.npmjs.com/package/react-native-url-polyfill to my project which resolved the issue.

Leaving here more for the benefit of future react native developers than anything, however, it might be a good win for some documentation since that seems to be all that's needed to get Meilisearch in more react native apps as far as I can tell :)

**Comment by emeagenciadigital** [comment]
For react native Algolia has this but I don’t know if you need a different library 

https://www.algolia.com/doc/guides/building-search-ui/going-further/native/react/

**Comment by emeagenciadigital** [comment]
> Still instant search, but with the react native components library (part of instant search)

Did you use meilisearch-react or plain instant-meilisearch or Algolia instant search  ? Please guide me on the library that was used , if you could share some code will be great .

**Comment by hgulersen** [comment]
@emeagenciadigital for react native, I used `@meilisearch/instant-meilisearch` and `react-instantsearch-native`. `react-instantsearch-native` is maintained by Algolia but you can easily use it with meilisearch as well. 

You can initialize the the client using  `@meilisearch/instant-meilisearch` and the hooks from `react-instantsearch-native` which is documented thoroughly here: https://www.algolia.com/doc/guides/building-search-ui/going-further/native/react-hooks/

Code to initialize the client: 

```
import { instantMeiliSearch } from "@meilisearch/instant-meilisearch";

const searchClient = instantMeiliSearch(
  <YOUR_URL>
  <YOUR_API_KEY
);
```

**Comment by leeadh** [comment]
Also asking for react native. I tried to do 

```
import React from "react";
import "instantsearch.css/themes/algolia-min.css";


import {
  Hits,
  SortBy,
  SearchBox,
  Pagination,
  Highlight,
  ClearRefinements,
  RefinementList,
  Configure,
  Snippet
} from "react-instantsearch-dom";
import { instantMeiliSearch } from '@meilisearch/instant-meilisearch';
import { InstantSearch } from 'react-instantsearch-hooks';

const searchClient = instantMeiliSearch(
  "http://xxx:7700/",
  "xxxxx"
);


const Discover = () => (
  
    <InstantSearch indexName="test" searchClient={searchClient}>

        <SearchBox />
        <Hits hitComponent={Hit} />

    </InstantSearch>

  
);


const Hit = ({ hit }) => {
  <div key={hit.id}>
    <div className="hitname">
      <Highlight attribute="Entity" hit={hit} />
    </div>
    
  </div>
};

```
but this didn't work. createConnector.js:186 Uncaught TypeError: this.props.contextValue.store.getState is not a function

any sample codes please?

**Comment by bidoubiwa** [comment]
Hey instead of using `react-instantsearch-hooks` can you try with this library:`react-instantsearch-native` ?

See [this doc](https://www.algolia.com/doc/guides/building-search-ui/going-further/native/react/)

**Comment by bidoubiwa** [comment]
not critical and stale, closing
