### ISSUE TITLE
TypeError: d is undefined

### ISSUE THREAD

**Issue by edpomacedo** [meilisearch/meilisearch-js-plugins#866]
Hello!

**Description**
The meilisearch-react only hydrates data into the App when the page is refreshed (Shift + F5). It does not hydrate the data when the app is accessed with mobile.

**Expected behavior**
It should hydrate the data without the refresh. Is should be visible and searchable when accessed with mobile.

**Current behavior**
The visitor needs to refresh the page to see the data and to perform any search when accessed via desktop. It shows only the components without any data when accessed via mobile.

**Screenshots or Logs**
```
TypeError: d is undefined
    searchResponse instant-meilisearch.umd.js:4122
    s instant-meilisearch.umd.js:77
    u instant-meilisearch.umd.js:58
    o instant-meilisearch.umd.js:48
    promise callback*s instant-meilisearch.umd.js:50
    i instant-meilisearch.umd.js:51
    i instant-meilisearch.umd.js:47
    searchResponse instant-meilisearch.umd.js:4097
    W instant-meilisearch.umd.js:4731
    s instant-meilisearch.umd.js:77
    u instant-meilisearch.umd.js:58
    i instant-meilisearch.umd.js:51
    i instant-meilisearch.umd.js:47
    W instant-meilisearch.umd.js:4715
    search instant-meilisearch.umd.js:4786
    s instant-meilisearch.umd.js:77
    u instant-meilisearch.umd.js:58
    i instant-meilisearch.umd.js:51
    i instant-meilisearch.umd.js:47
    search instant-meilisearch.umd.js:4776
    _search algoliasearch.helper.js:1299
    search algoliasearch.helper.js:150
    y createInstantSearchManager.js:232
    h createInstantSearchManager.js:464
    t createWidgetsManager.js:16
    promise callback*r utils.js:37
    registerWidget createWidgetsManager.js:23
    value createConnector.js:130
    React 6
    S scheduler.production.min.js:13
    C scheduler.production.min.js:14
    6813 scheduler.production.min.js:14
    Webpack 12
```

**Environment (please complete the following information):**
- OS: Ubuntu 20.04 LTS
- Browser: Mozilla Firefox for Ubuntu 105
- Meilisearch version: v.0.29.1
- instant-meilisearch version: v0.9.0
- instantsearch.js version: v.4.44.1

**Comment by bidoubiwa** [comment]
Hey @edpomacedo, I think this is due to the cache system in place. I'll add a system to disable that. 
Where did you get the `d is undefined` error?

**Comment by edpomacedo** [comment]
Hello @bidoubiwa ! Appreciated. This message was extracted from the Console.

**Comment by bidoubiwa** [comment]
Could not reproduce anymore, feel free to re-open if it is still a bug
